[experiment]
date = "2-12-21"
animal = "test"
block = 1

[pwm]
frequency = 15
chunk_size = 50
chunk_pause = 3000

[experiment.path]
output_folder = "~/data/hdd_"
suffixes = [ 0, 1, 2, 3,]
overwrite = false

[tiscam.path]
output_folder = "~/data/ssd"
prefix = "cam"
overwrite = true

[tiscam.logging]
stream_level = "info"
file_level = "debug"
gst_level = 1

[tiscam.pipeline]
max_buffers_queue = 30
compression_level = 0

[tiscam.properties.common]
"Override Scanning Mode" = 1
"Strobe Polarity" = false
"Offset X" = 0
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
"Trigger Global Reset Release" = false
"Strobe Delay" = 0
"Gain Auto Upper Limit" = 240
"Whitebalance Temperature" = 4000
"Trigger Mode" = false
"Auto Functions ROI Control" = true
"Highlight Reduction" = false
"Reverse X" = false
"Auto Functions ROI Preset" = "Center 50%"
"Whitebalance Green" = 64
"Gain Auto Lower Limit" = 0
"Offset Auto Center" = true
GPIn = 0
"Strobe Enable" = false
"Exposure Auto Reference" = 128
"Exposure Auto Upper Limit" = 33333
"Trigger Delay (us)" = 31
"Exposure Auto Upper Limit Auto" = true
"Trigger Polarity" = "Rising Edge"
Whitebalance = false
"Exposure Auto Lower Limit" = 60
"Whitebalance Auto Preset" = "Any"
"Reverse Y" = false
GPOut = 0
"Offset Y" = 0
Brightness = 180
"Exposure Auto" = false
"Exposure Time (us)" = 8333
Gain = 50
"Gain Auto" = false
"Strobe Duration" = 1
"Strobe Exposure" = false
"Whitebalance Auto" = false
"Whitebalance Blue" = 250
"Whitebalance Red" = 78

[tiscam.properties.44120512]

[tiscam.properties.44120513]

[tiscam.properties.44120535]

[tiscam.caps.common]
framerate = 120
color = true
width = 1920
height = 1080

[tiscam.caps.44120512]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120512"

[tiscam.caps.44120513]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120513"

[tiscam.caps.44120535]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120535"
