[properties]
"Auto Functions ROI Control" = true
"Strobe Delay" = 0
Gain = 86
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
"Gain Auto Upper Limit" = 240
"Offset Y" = 0
"Exposure Auto Upper Limit" = 33333
GPIn = 0
"Whitebalance Blue" = 64
GPOut = 0
"Exposure Auto" = false
"Trigger Global Reset Release" = false
"Exposure Auto Upper Limit Auto" = true
"Strobe Exposure" = true
"Offset Auto Center" = true
"Reverse X" = false
"Reverse Y" = false
"Whitebalance Temperature" = 4000
"Strobe Polarity" = false
"Trigger Mode" = false
"Exposure Time (us)" = 3856
"Gain Auto" = false
"Trigger Polarity" = "Rising Edge"
"Whitebalance Auto Preset" = "Any"
"Strobe Enable" = false
"Whitebalance Green" = 64
"Trigger Delay (us)" = 31
"Strobe Duration" = 100
Brightness = 240
"Exposure Auto Reference" = 128
"Whitebalance Red" = 64
"Gain Auto Lower Limit" = 0
"Offset X" = 0
"Whitebalance Auto" = false
"Exposure Auto Lower Limit" = 60
Whitebalance = false
"Auto Functions ROI Preset" = "Center 50%"
"Override Scanning Mode" = 0
"Highlight Reduction" = false

[general]
framerate = 120

[pwm]
frequency = 15
chunk_size = 50
chunk_pause = 3000

[cam_0.general]
accepted_width = [ 640, 1920, 640, 1920,]
accepted_height = [ 480, 1080, 480, 1080,]
color = true
width = 1920
height = 1080
serial = "44120535"

[cam_0.properties]
