[experiment]
date = "2-12-21"
animal = "test"
block = 1

[experiment.path]
output_folder = "~/bigdata"

[pwm]
frequency = 15
chunk_size = 50
chunk_pause = 3000

[tiscam.path]
output_folder = "~/data/"
prefix = "cam"
overwrite = true

[tiscam.logging]
stream_level = "info"
file_level = "debug"
gst_level = 1

[tiscam.pipeline]
max_buffers_queue = 30
compression_level = 0

[tiscam.properties.common]
"Trigger Delay (us)" = 31
"Auto Functions ROI Control" = true
"Trigger Global Reset Release" = false
"Reverse Y" = false
"Whitebalance Temperature" = 4000
"Whitebalance Green" = 64
"Offset Y" = 0
"Highlight Reduction" = false
"Exposure Auto Upper Limit" = 33333
"Strobe Delay" = 0
"Reverse X" = false
"Gain Auto Lower Limit" = 0
"Gain Auto Upper Limit" = 240
"Exposure Auto" = true
"Trigger Polarity" = "Rising Edge"
"Exposure Auto Lower Limit" = 60
"Exposure Auto Upper Limit Auto" = true
Brightness = 240
"Trigger Mode" = false
"Override Scanning Mode" = 0
"Exposure Auto Reference" = 128
"Strobe Enable" = false
"Strobe Exposure" = true
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
"Whitebalance Auto Preset" = "Any"
"Gain Auto" = true
GPOut = 0
"Strobe Duration" = 100
"Offset X" = 0
"Whitebalance Auto" = true
"Offset Auto Center" = true
"Strobe Polarity" = false
"Auto Functions ROI Preset" = "Center 50%"
GPIn = 0
Whitebalance = false

[tiscam.properties.44120512]
"Exposure Time (us)" = 8333
Gain = 94
"Whitebalance Blue" = 226
"Whitebalance Red" = 77

[tiscam.properties.44120513]
"Exposure Time (us)" = 333
Gain = 0
"Whitebalance Blue" = 64
"Whitebalance Red" = 64

[tiscam.properties.44120535]
"Exposure Time (us)" = 333
Gain = 0
"Whitebalance Blue" = 64
"Whitebalance Red" = 64

[tiscam.caps.common]
framerate = 120
height = 1080
color = true
width = 1920

[tiscam.caps.44120512]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120512"

[tiscam.caps.44120513]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120513"

[tiscam.caps.44120535]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120535"
