[properties]
"Whitebalance Auto Preset" = "Any"
"Strobe Enable" = false
"Exposure Auto Lower Limit" = 60
Gain = 122
"Whitebalance Red" = 73
"Gain Auto Lower Limit" = 0
"Whitebalance Blue" = 250
"Trigger Polarity" = "Rising Edge"
"Reverse X" = false
"Whitebalance Temperature" = 4000
"Exposure Time (us)" = 7142
"Gain Auto Upper Limit" = 240
"Whitebalance Auto" = true
"Auto Functions ROI Control" = true
"Highlight Reduction" = false
"Strobe Polarity" = false
"Offset X" = 0
"Offset Auto Center" = true
"Trigger Global Reset Release" = false
"Strobe Exposure" = true
"Reverse Y" = false
"Exposure Auto Reference" = 128
"Gain Auto" = true
"Strobe Delay" = 0
"Auto Functions ROI Preset" = "Center 50%"
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
"Whitebalance Green" = 64
GPIn = 0
"Trigger Mode" = false
"Offset Y" = 0
GPOut = 0
"Strobe Duration" = 100
"Trigger Delay (us)" = 31
Brightness = 240
Whitebalance = false
"Exposure Auto Upper Limit Auto" = true
"Exposure Auto" = true
"Override Scanning Mode" = 0
"Exposure Auto Upper Limit" = 33333

[general]
framerate = 120

[pwm]
frequency = 15
chunk_size = 50
chunk_pause = 3000

[cam_0.general]
accepted_width = [ 640, 1920, 640, 1920,]
accepted_height = [ 480, 1080, 480, 1080,]
color = true
width = 1920
height = 1080
serial = "44120535"

[cam_0.properties]
