[properties]
"Offset X" = 0
"Highlight Reduction" = false
"Strobe Exposure" = true
"Exposure Auto Upper Limit Auto" = true
"Strobe Duration" = 100
"Trigger Polarity" = "Falling Edge"
"Trigger Global Reset Release" = false
"Exposure Auto Lower Limit" = 1
"Override Scanning Mode" = 0
"Exposure Time (us)" = 33333
"Gain Auto" = false
"Exposure Auto Upper Limit" = 33333
"Auto Functions ROI Preset" = "Center 50%"
"Offset Auto Center" = true
GPOut = 0
"Exposure Auto Reference" = 100
"Trigger Mode" = true
"Reverse Y" = false
"Offset Y" = 0
"Strobe Polarity" = false
Gain = 4
"Gain Auto Lower Limit" = 0
"Exposure Auto" = false
"Strobe Enable" = false
Brightness = 469
GPIn = 0
"Trigger Delay (us)" = 31
"Reverse X" = false
"Auto Functions ROI Control" = true
"Strobe Delay" = 0
"Gain Auto Upper Limit" = 480

[general]
framerate = 120

[pwm]
frequency = 15
chunk_size = 50
chunk_pause = 3000

[cam_0.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "02020172"

[cam_0.properties]
"IMX Low-Latency Mode" = false
"Trigger Exposure Mode" = "Frame Start"

[cam_1.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "02020176"

[cam_1.properties]
"IMX Low-Latency Mode" = false
"Trigger Exposure Mode" = "Frame Start"

[cam_2.general]
accepted_width = [ 640, 1920, 640, 1920,]
accepted_height = [ 480, 1080, 480, 1080,]
color = true
width = 1920
height = 1080
serial = "44120513"

[cam_2.properties]
"Whitebalance Green" = 64
"Whitebalance Auto" = true
"Whitebalance Auto Preset" = "Any"
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
"Whitebalance Temperature" = 4000
"Whitebalance Blue" = 64
"Whitebalance Red" = 64
Whitebalance = false

[cam_3.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "49020380"

[cam_3.properties]
"IMX Low-Latency Mode" = false
"Trigger Exposure Mode" = "Frame Start"

[cam_4.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "49020382"

[cam_4.properties]
"IMX Low-Latency Mode" = false
"Trigger Exposure Mode" = "Frame Start"
