[pwm]
frequency = 30
chunk_size = 1800
chunk_pause = 3000

[tiscam]
serials = [ "02020172", "02020176", "45810316",]

[tiscam.path]
output_folder = "~/data/ssd/"
prefix = "cam"
overwrite = true

[tiscam.logging]
stream_level = "info"
file_level = "debug"
gst_level = 1

[tiscam.pipeline]
max_buffers_queue = 30
compression_level = 0

[tiscam.properties.common]
"Auto Functions ROI Control" = true
"Reverse X" = false
"Strobe Delay" = 0
"Trigger Global Reset Release" = false
"Exposure Auto" = false
"Exposure Auto Upper Limit" = 33333
"Override Scanning Mode" = 0
"Strobe Exposure" = true
"Trigger Mode" = true
"Gain Auto Upper Limit" = 480
"Strobe Duration" = 100
"Trigger Delay (us)" = 31
"Strobe Polarity" = false
"Offset Auto Center" = true
"Trigger Exposure Mode" = "Frame Start"
"Trigger Polarity" = "Rising Edge"
"Gain Auto Lower Limit" = 0
"Offset X" = 0
"Highlight Reduction" = false
GPOut = 0
"Gain Auto" = false
"Auto Functions ROI Preset" = "Center 50%"
"Exposure Auto Lower Limit" = 1
"Reverse Y" = false
"Offset Y" = 0
"Strobe Enable" = false

[tiscam.properties.02020172]
Brightness = 469
"Exposure Auto Reference" = 100
"Exposure Auto Upper Limit Auto" = true
"Exposure Time (us)" = 12954
GPIn = 0
Gain = 25
"IMX Low-Latency Mode" = false

[tiscam.properties.02020176]
Brightness = 0
"Exposure Auto Reference" = 100
"Exposure Auto Upper Limit Auto" = true
"Exposure Time (us)" = 10905
GPIn = 1
Gain = 59
"IMX Low-Latency Mode" = false

[tiscam.properties.45810316]
Brightness = 240
"Exposure Auto Reference" = 84
"Exposure Auto Upper Limit Auto" = false
"Exposure Time (us)" = 12954
GPIn = 0
Gain = 179
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
Whitebalance = false
"Whitebalance Auto" = true
"Whitebalance Auto Preset" = "Any"
"Whitebalance Blue" = 64
"Whitebalance Green" = 64
"Whitebalance Red" = 64
"Whitebalance Temperature" = 4000

[tiscam.caps.common]
framerate = 120
width = 1440
height = 1080

[tiscam.caps.02020172]
accepted_width = [ 1440, 1440, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
color = false
serial = "02020172"

[tiscam.caps.02020176]
accepted_width = [ 1440, 1440, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
color = false
serial = "02020176"

[tiscam.caps.45810316]
accepted_width = [ 1440, 1440, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
color = true
serial = "45810316"
