[pwm]
frequency = 100
chunk_size = 500
chunk_pause = 100

[tiscam]
serials = [ "44120512", "44120513", "44120535",]

[tiscam.path]
output_folder = "~/data/ssd/"
prefix = "cam"
overwrite = true

[tiscam.logging]
stream_level = "warning"
file_level = "debug"
gst_level = 1

[tiscam.pipeline]
max_buffers_queue = 30
compression_level = 0

[tiscam.properties.common]
"Auto Functions ROI Preset" = "Center 50%"
"Exposure Auto Lower Limit" = 60
Brightness = 240
Gain = 50
"Whitebalance Green" = 64
"Trigger Delay (us)" = 31
"Strobe Delay" = 0
"Exposure Auto" = false
"Trigger Mode" = true
"Exposure Auto Upper Limit" = 33333
"Whitebalance Temperature" = 4000
"Reverse X" = false
GPIn = 0
"Override Scanning Mode" = 0
"Strobe Enable" = false
"Gain Auto" = false
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
"Whitebalance Blue" = 255
"Whitebalance Red" = 73
"Highlight Reduction" = false
"Gain Auto Upper Limit" = 240
"Strobe Exposure" = true
"Exposure Time (us)" = 7000
"Gain Auto Lower Limit" = 0
"Reverse Y" = false
"Offset Auto Center" = true
"Offset Y" = 0
"Exposure Auto Reference" = 128
"Trigger Polarity" = "Rising Edge"
"Auto Functions ROI Control" = true
"Strobe Polarity" = false
"Trigger Global Reset Release" = false
GPOut = 0
"Whitebalance Auto" = true
"Offset X" = 0
"Exposure Auto Upper Limit Auto" = true
"Strobe Duration" = 100
"Whitebalance Auto Preset" = "Any"
Whitebalance = false

[tiscam.properties.44120512]
[tiscam.properties.44120513]
[tiscam.properties.44120535]

[tiscam.caps.common]
framerate = 120
height = 1080
width = 1920
color = true

[tiscam.caps.44120512]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120512"

[tiscam.caps.44120513]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120513"

[tiscam.caps.44120535]
accepted_width = [ 1920, 1920, 640, 640,]
accepted_height = [ 1080, 1080, 480, 480,]
serial = "44120535"
