[properties]
GPOut = 0
"Exposure Auto Upper Limit Auto" = true
"Strobe Polarity" = false
"Exposure Auto Lower Limit" = 1
"Trigger Polarity" = "Falling Edge"
"Strobe Delay" = 0
"Strobe Duration" = 100
"Highlight Reduction" = false
"Trigger Delay (us)" = 31
"Gain Auto" = false
Brightness = 429
"Offset Auto Center" = true
"Strobe Enable" = false
"Exposure Auto" = false
"Reverse Y" = false
"Offset X" = 0
"Exposure Time (us)" = 15000
"Auto Functions ROI Preset" = "Center 50%"
Gain = 0
"Reverse X" = false
"Auto Functions ROI Control" = true
"Exposure Auto Upper Limit" = 33333
GPIn = 0
"Override Scanning Mode" = 0
"Exposure Auto Reference" = 100
"Trigger Global Reset Release" = false
"Trigger Mode" = true
"Gain Auto Upper Limit" = 480
"Strobe Exposure" = true
"Gain Auto Lower Limit" = 0
"Offset Y" = 0

[general]
framerate = 120

[pwm]
frequency = 20
chunk_size = 0
chunk_pause = 3000

[cam_0.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "02020172"

[cam_0.properties]
"Auto Functions ROI Control" = true
"Auto Functions ROI Preset" = "Center 50%"
Brightness = 429
"Exposure Auto" = false
"Exposure Auto Lower Limit" = 1
"Exposure Auto Reference" = 100
"Exposure Auto Upper Limit" = 33333
"Exposure Auto Upper Limit Auto" = true
"Exposure Time (us)" = 15000
GPIn = 0
GPOut = 0
Gain = 0
"Gain Auto" = false
"Gain Auto Lower Limit" = 0
"Gain Auto Upper Limit" = 480
"Highlight Reduction" = false
"IMX Low-Latency Mode" = false
"Offset Auto Center" = true
"Offset X" = 0
"Offset Y" = 0
"Override Scanning Mode" = 0
"Reverse X" = false
"Reverse Y" = false
"Strobe Delay" = 0
"Strobe Duration" = 100
"Strobe Enable" = false
"Strobe Exposure" = true
"Strobe Polarity" = false
"Trigger Delay (us)" = 31
"Trigger Exposure Mode" = "Frame Start"
"Trigger Global Reset Release" = false
"Trigger Mode" = true
"Trigger Polarity" = "Falling Edge"

[cam_1.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "02020176"

[cam_1.properties]
"Auto Functions ROI Control" = true
"Auto Functions ROI Preset" = "Center 50%"
Brightness = 234
"Exposure Auto" = false
"Exposure Auto Lower Limit" = 1
"Exposure Auto Reference" = 100
"Exposure Auto Upper Limit" = 33333
"Exposure Auto Upper Limit Auto" = true
"Exposure Time (us)" = 20000
GPIn = 0
GPOut = 0
Gain = 4
"Gain Auto" = false
"Gain Auto Lower Limit" = 0
"Gain Auto Upper Limit" = 480
"Highlight Reduction" = false
"IMX Low-Latency Mode" = false
"Offset Auto Center" = true
"Offset X" = 0
"Offset Y" = 0
"Override Scanning Mode" = 0
"Reverse X" = false
"Reverse Y" = false
"Strobe Delay" = 0
"Strobe Duration" = 100
"Strobe Enable" = false
"Strobe Exposure" = true
"Strobe Polarity" = false
"Trigger Delay (us)" = 31
"Trigger Exposure Mode" = "Frame Start"
"Trigger Global Reset Release" = false
"Trigger Mode" = true
"Trigger Polarity" = "Falling Edge"

[cam_2.general]
accepted_width = [ 640, 1920, 640, 1920,]
accepted_height = [ 480, 1080, 480, 1080,]
color = true
width = 1920
height = 1080
serial = "44120513"

[cam_2.properties]
"Auto Functions ROI Control" = true
"Auto Functions ROI Preset" = "Center 50%"
Brightness = 150
"Exposure Auto" = false
"Exposure Auto Lower Limit" = 60
"Exposure Auto Reference" = 100
"Exposure Auto Upper Limit" = 33333
"Exposure Auto Upper Limit Auto" = true
"Exposure Time (us)" = 15000
GPIn = 0
GPOut = 0
Gain = 46
"Gain Auto" = false
"Gain Auto Lower Limit" = 0
"Gain Auto Upper Limit" = 240
"Highlight Reduction" = false
"Offset Auto Center" = true
"Offset X" = 0
"Offset Y" = 0
"Override Scanning Mode" = 0
"Reverse X" = false
"Reverse Y" = false
"Strobe Delay" = 0
"Strobe Duration" = 100
"Strobe Enable" = false
"Strobe Exposure" = true
"Strobe Polarity" = false
"Trigger Delay (us)" = 31
"Trigger Global Reset Release" = false
"Trigger Mode" = true
"Trigger Polarity" = "Falling Edge"
"White Balance Temperature Preset" = "Cool White Fluorescent Light"
Whitebalance = false
"Whitebalance Auto" = true
"Whitebalance Auto Preset" = "Any"
"Whitebalance Blue" = 223
"Whitebalance Green" = 64
"Whitebalance Red" = 70
"Whitebalance Temperature" = 4000

[cam_3.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "49020380"

[cam_3.properties]
"Auto Functions ROI Control" = true
"Auto Functions ROI Preset" = "Center 50%"
Brightness = 469
"Exposure Auto" = false
"Exposure Auto Lower Limit" = 1
"Exposure Auto Reference" = 100
"Exposure Auto Upper Limit" = 33333
"Exposure Auto Upper Limit Auto" = true
"Exposure Time (us)" = 20000
GPIn = 0
GPOut = 0
Gain = 0
"Gain Auto" = false
"Gain Auto Lower Limit" = 0
"Gain Auto Upper Limit" = 480
"Highlight Reduction" = false
"IMX Low-Latency Mode" = false
"Offset Auto Center" = true
"Offset X" = 0
"Offset Y" = 0
"Override Scanning Mode" = 0
"Reverse X" = false
"Reverse Y" = false
"Strobe Delay" = 0
"Strobe Duration" = 100
"Strobe Enable" = false
"Strobe Exposure" = true
"Strobe Polarity" = false
"Trigger Delay (us)" = 31
"Trigger Exposure Mode" = "Frame Start"
"Trigger Global Reset Release" = false
"Trigger Mode" = true
"Trigger Polarity" = "Falling Edge"

[cam_4.general]
accepted_width = [ 1440, 640, 1440, 640,]
accepted_height = [ 1080, 480, 1080, 480,]
color = false
width = 1440
height = 1080
serial = "49020382"

[cam_4.properties]
"Auto Functions ROI Control" = true
"Auto Functions ROI Preset" = "Center 50%"
Brightness = 469
"Exposure Auto" = false
"Exposure Auto Lower Limit" = 1
"Exposure Auto Reference" = 100
"Exposure Auto Upper Limit" = 33333
"Exposure Auto Upper Limit Auto" = true
"Exposure Time (us)" = 22776
GPIn = 0
GPOut = 0
Gain = 0
"Gain Auto" = false
"Gain Auto Lower Limit" = 0
"Gain Auto Upper Limit" = 480
"Highlight Reduction" = false
"IMX Low-Latency Mode" = false
"Offset Auto Center" = true
"Offset X" = 0
"Offset Y" = 0
"Override Scanning Mode" = 0
"Reverse X" = false
"Reverse Y" = false
"Strobe Delay" = 0
"Strobe Duration" = 100
"Strobe Enable" = false
"Strobe Exposure" = true
"Strobe Polarity" = false
"Trigger Delay (us)" = 31
"Trigger Exposure Mode" = "Frame Start"
"Trigger Global Reset Release" = false
"Trigger Mode" = true
"Trigger Polarity" = "Falling Edge"
