#!/usr/bin/env python

import toml
import logging
import argparse
from pathlib import Path
from shutil import copyfile
from experiment.helpers import parse_config_path


from experiment.server import TmpConfig
def generate_target_video_dirs(config):
    "Return a list of all the absolute paths were videos are to be stored"
    target_root = Path(TmpConfig(self.config["experiment"]["tmp"]["storage"])).expanduser().absolute()
    serials = config["tiscam"]["serials"]
    prefix = config["tiscam"]["path"]["prefix"]
    
    video_parent = Path(root).expanduser().absolute() / config["experiment"]["video_dir"]
    return [video_path / (prefix + "_" + serial) for serial in serials]


config_path = parse_config_path()
config = Config(config_path).read()

exist_ok = config["experiment"]["overwrite"]

for path in generate_target_video_dirs():
    p.mkdir(parents=True, exist_ok=exist_ok)
