#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
from experiment.helpers import parse_config_path, read_config

config_path = parse_config_path()
configs = read_config(config_path)

GPIO.setmode(GPIO.BCM)

pump_pin = int(configs["experiment"]["pins"]["pump"])
GPIO.setup(pump_pin, GPIO.OUT)

while True:
    GPIO.output(pump_pin, True)
    time.sleep(0.05)
    GPIO.output(pump_pin, False)
    time.sleep(0.05)
