#!/usr/bin/env bash
mkdir -p ~/pickles/cam0
mkdir -p ~/pickles/cam1
mkdir -p ~/pickles/cam2
mkdir -p ~/pickles/cam3
mkdir -p ~/pickles/cam4
rm ~/pickles/cam*/**

scp dracaufeu:~/data/less_cam/cam_02020172/*.pickle ~/pickles/cam0
scp dracaufeu:~/data/less_cam/cam_02020176/*.pickle ~/pickles/cam1
scp dracaufeu:~/data/less_cam/cam_45810316/*.pickle ~/pickles/cam2
scp dracaufeu:~/data/less_cam/cam_49020382/*.pickle ~/pickles/cam3
scp dracaufeu:~/data/less_cam/cam_49020380/*.pickle ~/pickles/cam4
