#!/usr/bin/env bash
mkdir -p ~/pickles/cam0
mkdir -p ~/pickles/cam1
mkdir -p ~/pickles/cam2
mkdir -p ~/pickles/cam3
mkdir -p ~/pickles/cam4
rm ~/pickles/cam*/**

scp dracaufeu:~/data/cam0/*.pickle ~/pickles/cam0
scp dracaufeu:~/data/cam1/*.pickle ~/pickles/cam1
scp dracaufeu:~/data/cam2/*.pickle ~/pickles/cam2
scp dracaufeu:~/data/cam3/*.pickle ~/pickles/cam3
scp dracaufeu:~/data/cam4/*.pickle ~/pickles/cam4

scp dracaufeu:~/data/cam0/record.log ~/pickles/cam0
scp dracaufeu:~/data/cam1/record.log ~/pickles/cam1
scp dracaufeu:~/data/cam2/record.log ~/pickles/cam2
scp dracaufeu:~/data/cam3/record.log ~/pickles/cam3
scp dracaufeu:~/data/cam4/record.log ~/pickles/cam4
