#!/usr/bin/env bash

config="mnt/configs.toml"

serials=$(tcam-ctrl -l | awk '{print $5}')

for serial in $serials; do
	python -m tiscam.record -c $config -s $serial &
	PID=$!
	echo $PID
done

wait $PID
