#!/usr/bin/env bash

config="~/phd/api/setup/config.toml"

python -m tiscam.record -c $config -s 44120512 &
PID12=$!
python -m tiscam.record -c $config -s 44120513 &
PID13=$!

trap "kill $PID12 && kill $PID13" EXIT
wait $PID12
