#!/usr/bin/env bash

config="~/phd/api/setup/config.toml"

python -m tiscam.record -c $config -s 44120512 &
PID12=$!
python -m tiscam.record -c $config -s 44120513 &
PID13=$!

trap "echo 'Killing camera processes'; kill -2 $PID12 && kill -2 $PID13 && exit 1" EXIT
while [ -d /proc/$PID12 -a -d /proc/$PID13 ]; do
	sleep 1
done
echo 'One or more camera processes has stopped'
exit 1
